# Generated by Django 4.0.3 on 2022-03-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='modified',
        ),
    ]
