# Generated by Django 4.0.3 on 2022-03-16 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_roomtype_created_remove_roomtype_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date booking')),
                ('end_date', models.DateField(verbose_name='End Date booking')),
                ('num_guest', models.IntegerField(default=1)),
                ('contact_name', models.CharField(max_length=200, null=b'I00\n')),
                ('contact_email', models.CharField(max_length=200, null=b'I00\n')),
                ('contact_phone', models.CharField(max_length=20, null=b'I00\n')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_reference', models.CharField(max_length=40)),
                ('room_number', models.IntegerField(null=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roomtype')),
            ],
        ),
    ]
